"""Collection of seed utterances for each administrative intent.

These are written by us (no public university-admin intent dataset exists), so the
seed set is collected by a survey. Augmentation happens later, after the train/test split.
"""

SEED_UTTERANCES: dict[str, list[str]] = {
    "certificates": [
        "How do I get a bonafide certificate?",
        "I need a bonafide certificate for my bank loan.",
        "Where can I apply for a character certificate?",
        "I need a migration certificate after finishing my degree.",
        "How long does it take to get a no objection certificate?",
        "Can I get a provisional degree certificate before convocation?",
        "What documents are required for a course completion certificate?",
        "I want a certificate stating I am a student here for my visa application.",
        "Please tell me the process to obtain a domicile verification letter from the university.",
        "How do I request a duplicate degree certificate? I lost the original.",
        "Who issues the medium of instruction certificate?",
        "I need an NOC for an internship, whom do I contact?",
        "What is the fee for a bonafide certificate?",
        "Where do I collect my passing certificate?",
        "Need a conduct certificate for a scholarship form.",
        "Can I apply for a certificate online or do I have to visit the office?",
        "My degree certificate has a spelling mistake in my name, how do I correct it?",
        "How many days for a study certificate to be issued?",
        "I need attested copies of my degree certificate.",
        "Is a bonafide letter available the same day?",
    ],
    "transcripts": [
        "How can I get my official transcript?",
        "I need my transcripts sent to a university abroad.",
        "What is the process to apply for a semester-wise transcript?",
        "How much does a transcript cost?",
        "Can the university send my transcript directly to WES?",
        "I need a marksheet copy for all eight semesters.",
        "Where do I request a consolidated grade card?",
        "How long will it take to receive my transcript after applying?",
        "I need a sealed transcript envelope for my master's application.",
        "Can I download my transcript from the student portal?",
        "Please guide me on requesting a transcript for higher studies in Germany.",
        "How do I get a duplicate marksheet?",
        "I want a CGPA to percentage conversion letter along with my transcript.",
        "Who signs the official academic transcript?",
        "How many copies of the transcript can I order at once?",
        "My transcript request is still pending, who do I follow up with?",
        "Can I get an unofficial transcript instantly?",
        "I need a transcript for my graduate school admission.",
        "Do you provide transcripts in a sealed cover with the university stamp?",
        "What documents do I submit to get my mark statement?",
    ],
    "id_cards": [
        "I lost my ID card. What should I do?",
        "My student ID card got stolen yesterday.",
        "How do I apply for a replacement ID card?",
        "My ID card is damaged and the barcode does not scan.",
        "Where can I get a new identity card made?",
        "I forgot my ID card at home, can I still enter the library?",
        "What is the fee for a duplicate ID card?",
        "My photo on the ID card is wrong, how can I change it?",
        "How long does it take to get a new student ID?",
        "I have not received my ID card yet even after two months of admission.",
        "Do I need to file an FIR for a lost ID card?",
        "Faculty ID card renewal process please.",
        "The chip on my ID card is not working at the gate.",
        "Who do I contact for an ID card correction?",
        "Can I get a temporary ID card while the new one is being printed?",
        "I misplaced my identity card in the canteen.",
        "Need a new library card and ID card.",
        "My ID card expired, how do I renew it?",
        "Where do I submit the form for a lost ID?",
        "I broke my ID card, please help me get another one.",
    ],
    "hostel": [
        "How do I apply for hostel accommodation?",
        "When will the hostel room allotment list be released?",
        "I want to change my hostel room.",
        "What are the hostel fees for a single occupancy room?",
        "How do I get a hostel leave permission for the weekend?",
        "What is the hostel curfew timing?",
        "The water heater in my hostel room is not working, who should I complain to?",
        "Can I bring a guest to the hostel?",
        "I need a hostel no dues certificate before vacating.",
        "How do I cancel my hostel booking?",
        "Are first year students allowed to stay in the hostel?",
        "What documents are needed for hostel admission?",
        "Is there a mess fee refund if I leave the hostel midway?",
        "I want to switch from a shared room to a single room.",
        "Where is the hostel warden's office?",
        "How do I pay my hostel security deposit?",
        "I need to extend my stay at the hostel during summer vacation.",
        "There is a roommate issue in my hostel, whom do I report to?",
        "What are the rules for hostel night out?",
        "Can I get an off-campus permission instead of the hostel?",
    ],
    "examinations": [
        "When will the end semester exam timetable be released?",
        "How do I apply for revaluation of my answer sheet?",
        "I missed my exam due to illness, can I get a re-exam?",
        "Where can I download my hall ticket?",
        "What is the process to apply for a supplementary exam?",
        "How do I check my exam results?",
        "I want to see my evaluated answer script.",
        "What is the last date to fill the examination form?",
        "There is a clash between two of my exam papers, what should I do?",
        "How do I apply for a backlog exam?",
        "My hall ticket has the wrong subject code.",
        "What is the fee for revaluation?",
        "Can I get an exam center change?",
        "When will the internal assessment marks be published?",
        "I failed one subject, how do I reappear for the exam?",
        "Are calculators allowed in the end semester examination?",
        "How do I apply for makeup exams for medical reasons?",
        "The result shows absent even though I appeared for the paper.",
        "What is the passing criteria for the semester exams?",
        "Who do I contact about the mid semester exam schedule?",
    ],
    "fees": [
        "How do I pay my semester fee online?",
        "What is the last date to pay tuition fees without a fine?",
        "I paid the fees but it is not reflecting on the portal.",
        "Can I pay my fees in installments?",
        "I want a refund of my fee since I withdrew from the course.",
        "Where can I download my fee receipt?",
        "What is the late fee penalty for delayed payment?",
        "Money got deducted from my account but the payment failed.",
        "How much is the fee for the second year?",
        "Is there a fee waiver for students with financial difficulty?",
        "I need a fee structure document for my education loan.",
        "Can I pay the exam fee via demand draft?",
        "My fee receipt shows the wrong amount.",
        "What payment modes are accepted by the accounts office?",
        "Do I have to pay hostel fees along with tuition fees?",
        "How can I check my pending dues?",
        "Is GST charged on the tuition fee?",
        "I was charged twice for the same semester fee.",
        "Who do I talk to about fee concessions?",
        "What is the fee for the re-admission after a break?",
    ],
    "scholarships": [
        "What scholarships are available for undergraduate students?",
        "How do I apply for the merit scholarship?",
        "What is the eligibility for the government scholarship for SC/ST students?",
        "When will my scholarship amount be credited?",
        "What documents are required for a need-based financial aid application?",
        "Is there any scholarship for girl students in engineering?",
        "I did not receive my scholarship this semester.",
        "How do I renew my scholarship for the next year?",
        "What GPA do I need to keep my scholarship?",
        "Where can I check the status of my scholarship application?",
        "Is a fee waiver scholarship available for sports achievers?",
        "The last date for the scholarship application has passed, can I still apply?",
        "Are there any foreign study scholarships listed by the university?",
        "Do I need an income certificate to apply for a scholarship?",
        "Can I get both a merit scholarship and an education loan?",
        "Who is the coordinator for the scholarship cell?",
        "My scholarship was rejected, how can I appeal?",
        "I want to apply for a research fellowship at the university.",
        "What is the scholarship amount for toppers of the department?",
        "Tell me about the minority scholarship scheme.",
    ],
    "attendance": [
        "What is the minimum attendance required to sit for exams?",
        "My attendance is 68 percent, will I be detained?",
        "How do I apply for attendance condonation?",
        "The portal shows me absent although I was present in class.",
        "I was on medical leave, how can I get my attendance adjusted?",
        "Where can I check my subject-wise attendance?",
        "Can I get attendance for the days I participated in a college fest?",
        "Who marks the attendance for lab sessions?",
        "I need to submit a medical certificate for my absence.",
        "What happens if my attendance falls below 75 percent?",
        "Is there any relaxation in attendance for sports representatives?",
        "How do I report a mistake in my attendance record?",
        "Can duty leave be counted as present?",
        "My professor did not update my attendance for the last month.",
        "How is attendance calculated for the semester?",
        "What is the last date to submit the attendance condonation form?",
        "Is attendance mandatory for the online classes?",
        "I have shortage of attendance in one subject, what are my options?",
        "How can faculty upload attendance for a batch?",
        "Do I get attendance for the guest lecture?",
    ],
    "academic_registration": [
        "How do I register for next semester's courses?",
        "When does the course registration window open?",
        "I want to add an elective after the registration deadline.",
        "How can I drop a course after registration?",
        "What is the maximum number of credits I can register for?",
        "I could not register on time because of a portal error.",
        "How do I change my major or branch?",
        "What are the prerequisites for registering for advanced algorithms?",
        "How do I enroll in a minor program?",
        "Can I take a course from another department as an open elective?",
        "I am a new student, how do I complete my admission registration?",
        "My registration is stuck at pending approval from the advisor.",
        "How do I register for a summer course?",
        "I want to withdraw from the semester, what is the procedure?",
        "How do I register for the project or thesis credits?",
        "What is the process for re-registering after a semester break?",
        "The elective I wanted is full, can I get added to the waitlist?",
        "Where can I see the list of courses offered this semester?",
        "How do I get my course registration form signed by my faculty advisor?",
        "What is the late registration fee?",
    ],
    "out_of_scope": [
        "What is the weather like today?",
        "Tell me a joke.",
        "Who won the cricket match yesterday?",
        "Can you recommend a good movie?",
        "What is the capital of France?",
        "How do I cook pasta?",
        "Explain quantum computing to me.",
        "What is the best programming language to learn?",
        "Write a poem about the ocean.",
        "How far is the moon from the earth?",
        "Book me a flight to Delhi.",
        "What is the meaning of life?",
        "Play some music.",
        "Which phone should I buy?",
        "Translate hello into Spanish.",
        "What is the stock price of Tata Motors?",
        "How do I lose weight fast?",
        "Who is the prime minister of India?",
        "Recommend a good restaurant near me.",
        "What time is it in London?",
    ],
}
